repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Or a specific commit hash
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.5 # Or a specific commit hash
    hooks:
      - id: clang-format
        args: [--style=file] # Or a specific style name
        files: \.(cpp|h|cxx|hpp|inl)$
